'use client';

import { useState } from 'react';
// import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import '@/styles/globals.scss';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mobileMenu, setMobileMenu] = useState<boolean>(false);

  const handleDisplayMobileMenu: () => void = () => {
    setMobileMenu((current) => !current);
  };
  return (
    <html lang="fr" id={mobileMenu ? 'scrollOff' : ''}>
      <body>
        <Navbar mobileMenu={mobileMenu} handleDisplayMobileMenu={handleDisplayMobileMenu} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
