/* eslint-disable @next/next/no-page-custom-font */

'use client';

import { useState } from 'react';
// import type { Metadata } from 'next';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import 'app.css';
import '@/styles/globals.scss';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mobileMenu, setMobileMenu] = useState<boolean>(false);

  const handleDisplayMobileMenu: () => void = () => {
    setMobileMenu((current) => !current);
  };
  return (
    <html lang="fr" id={mobileMenu ? 'scrollOff' : ''}>
      <Head>
        <title>SnapEats</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Playwrite+DK+Uloopet:wght@100..400&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </Head>
      <body>
        <Navbar mobileMenu={mobileMenu} handleDisplayMobileMenu={handleDisplayMobileMenu} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
